### ISSUE TITLE
Decide on a specific scope of PyMARE

### ISSUE THREAD

**Issue by nicholst** [neurostuff/PyMARE#21] opened 2020-03-07 17:12 UTC
Need to clarify, once and for all, which meta-analysis functionality will and will not be supported by PyMARE.

Presently we have, for continuous Gaussian responses
* Fixed effects meta-regression
* Random effects meta-regression
* Random effects meta-regression, where study-level variance is unknown
* "Combining" measures, Fishers & Stouffer's (coming soon)

The plan is to provide conversion tools so that the following types that don't exactly fit into that framework can be converted and used:
* Correlation coefficients
* Cohen's d effect sizes & standardised mean differences

The long list of possible to-be-included tools include:
* Cochran's Q - Heterogeneity statistic
* 'Stouffer's Meta Regression', basically a fixed effects meta-analysis on Z-scores -- not a standard method and never considered in traditional meta-analysis, but might have a use in NMA
* 'Stouffer's Random Effects Regression' - Analyze Z-scores as if they were Gaussian response with homogeneous variance
* Permutation - But need to consider how to do this vectorised, considering the NMA use case.

(NMA=Neuroimaging Meta Analysis)

**Comment by tyarkoni** [comment] 2020-03-09 17:21
Cochran's Q is already used to find CIs for most of the methods, so exposing it to users is easy.

Permutation is definitely on the agenda, but vectorization may not be, depending on what you mean. It should be easy to vectorize the permutation generation, and we should definitely do that. But if you're talking about vectorizing over datasets (e.g., making it efficient to do multiple voxels at the same time), that's probably not in scope, as I suspect it would require a lot of optimization work. (The main concern here is that I don't know that this could be done generically—I'm guessing we'd need to write custom vectorized code for each model.)

Stouffer's meta-regression seems sensible to support by extending the Stouffers estimator (once implemented), as that's the same pattern we use for all the other models (i.e., it just depends on whether the user passes in `X` or not). Not sure about 'Stouffer's RFX', but we can re-evaluate later.

**Comment by tyarkoni** [comment] 2020-05-05 01:51
@nicholst I'm closing this because everything on your original list is now already implemented, or should be straightforward. The exception is vectorized permutation testing, which *is* implemented in 2d, but would be much harder to do in 3d (aside from complicating the linear algebra, we'd also need to operate in batches or memory-map, which would introduce an added level of complexity). So doing, e.g., 400 ROIs is pretty speedy right now, but doing 200k voxels, not so much.

**Closed by tyarkoni** 2020-05-05 01:51 UTC
